apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: bzflag-server
  name: bzflag-server
  namespace: games
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bzflag-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bzflag-server
    spec:
      volumes:
        - name: bzflag-config
          configMap:
            name: bzflag-server-config
      containers:
        - image: quay.io/jiphex/bzflag-server:latest
          imagePullPolicy: Always
          name: bzflag-server
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
          volumeMounts:
            - name: bzflag-config
              mountPath: /etc/bzflag
          args:
            - -conf
            - /etc/bzflag/server.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
