apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: bzflag-server
  name: bzflag-server
  namespace: games
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bzflag-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bzflag-server
    spec:
      containers:
        - image: quay.io/jiphex/bzflag-server:latest
          imagePullPolicy: Always
          name: bzflag-server
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
